### ISSUE TITLE
预处理部分问题

### ISSUE THREAD

**Issue by ChanaHuang** [HustMinsLab/DAPrompt#2]
请问EventStoryLine_20221012.py文件里面的.tab 文件怎么获得？原始的EventStoryLine数据集没有这种文件格式

**Comment by hasakioho** [comment]
> 请问EventStoryLine_20221012.py文件里面的.tab 文件怎么获得？原始的EventStoryLine数据集没有这种文件格式

那个文件应该是用来处理出事件对的关系类型的，直接在预处理的代码里把事件对关系处理加上就可以

**Comment by ytWu1314** [comment]
运行完EventStoryLine_20221012.py，我把得到的data存到一个.csv中，但是发现relation这一列的数据全是NONE，如果是这样子，不是没有ECI,Cause这部分的关系吗？
